# Generated by Django 5.2.7 on 2025-10-10 17:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('level', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('page_found', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(max_length=300, upload_to=core.models.resource_upload_to),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='portada',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='covers/'),
        ),
    ]
