# Generated by Django 5.2.7 on 2025-10-13 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_forumthread_forumreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Una breve descripción sobre ti, tu experiencia y cómo puedes ayudar.')),
                ('verificado', models.BooleanField(default=False, help_text='Marcar si este es un tutor verificado (ej. profesor, egresado).')),
                ('activo', models.BooleanField(default=False, help_text='Marcar si el usuario está disponible para dar tutorías.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('materias', models.ManyToManyField(blank=True, help_text='Selecciona las materias que dominas.', related_name='tutores', to='core.ramo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Tutor',
                'verbose_name_plural': 'Perfiles de Tutores',
                'ordering': ['user__username'],
            },
        ),
    ]
