# Generated by Django 5.2.7 on 2025-10-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tutoringrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalPDF',
        ),
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ['creado_en']},
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AlterModelOptions(
            name='tutoringrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='ramo',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='descargas',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='portada',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='publicado',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='vistas',
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='materias',
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='materias',
            field=models.CharField(blank=True, help_text='Escribe tus habilidades o materias separadas por comas.', max_length=255),
        ),
    ]
