# Generated by Django 5.2.7 on 2025-10-24 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_externalpdf_alter_forumreply_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='coffee_link',
            field=models.URLField(blank=True, help_text="Enlace a MercadoPago, Ko-fi, etc. para 'Invítale un café'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tutor', 'student')},
            },
        ),
    ]
