# Generated by Django 5.2.7 on 2025-10-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tutorprofile_coffee_link_alter_tutorprofile_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='tipo_tutor',
            field=models.CharField(choices=[('voluntario', 'Ayuda Voluntaria (Gratis)'), ('donacion', 'A base de Donaciones (Invítame un café ☕)'), ('privado', 'Tarifa Privada (Arreglo por interno)')], default='voluntario', help_text='Define cómo ofreces tus tutorías.', max_length=20),
        ),
    ]
