# Generated by Django 5.2.7 on 2025-10-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tutorprofile_tipo_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringrequest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ramo'),
        ),
    ]
