# Generated by Django 5.2.7 on 2025-10-24 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_tutoringrequest_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre corto y descriptivo para la sala (ej. 'Certamen 2 Cálculo')", max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción más detallada (opcional)')),
                ('es_temporal', models.BooleanField(default=False, help_text='Marcar si es una sesión rápida o temporal')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Si es temporal, ¿cuándo debería desaparecer?', null=True)),
                ('enlace_videollamada', models.URLField(blank=True, help_text='Enlace a Google Meet, Jitsi, Discord, etc.', max_length=255)),
                ('enlace_pizarra', models.URLField(blank=True, help_text='Enlace a Excalidraw, Miro, etc.', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_study_rooms', to=settings.AUTH_USER_MODEL)),
                ('ramo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_rooms', to='core.ramo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
